/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package View;

import Controller.SQLite;
import java.awt.Color;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author Allen
 */
public class ForgetPassword1 extends javax.swing.JPanel {
    
    public Frame frame;
    private SQLite sqlite;
    /**
     * Creates new form ForgetPassword1
     */
    public ForgetPassword1() {
        initComponents();
    }
    
    public void init(SQLite sqlite) {
        this.sqlite = sqlite;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        usernameFld = new javax.swing.JTextField();
        passwordFld = new javax.swing.JPasswordField();
        questionFld = new javax.swing.JTextField();
        question2Fld = new javax.swing.JTextField();
        nextBtn1 = new javax.swing.JButton();
        confirmPasswordFld = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        passStrength = new javax.swing.JProgressBar();
        nextBtn = new javax.swing.JButton();
        passStrengthLabel = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        updateBtn = new javax.swing.JButton();
        passToolTip = new javax.swing.JTextArea();
        passToolTip.setVisible(false);

        usernameFld.setBackground(new java.awt.Color(240, 240, 240));
        usernameFld.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        usernameFld.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        usernameFld.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true), "USERNAME", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 12))); // NOI18N
        usernameFld.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                usernameFldKeyReleased(evt);
            }
        });

        passwordFld.setBackground(new java.awt.Color(240, 240, 240));
        passwordFld.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        passwordFld.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        passwordFld.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true), "Password", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 12))); // NOI18N
        passwordFld.setVisible(false);
        passwordFld.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                passwordFldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                passwordFldFocusLost(evt);
            }
        });
        passwordFld.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                passwordFldKeyReleased(evt);
            }
        });

        questionFld.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                questionFldMouseClicked(evt);
            }
        });
        questionFld.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                questionFldActionPerformed(evt);
            }
        });
        questionFld.setVisible(false);

        question2Fld.setVisible(false);

        nextBtn1.setBackground(new java.awt.Color(0, 0, 0));
        nextBtn1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        nextBtn1.setForeground(new java.awt.Color(255, 255, 255));
        nextBtn1.setText("Next");
        nextBtn1.setVisible(false);
        nextBtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextBtn1ActionPerformed(evt);
            }
        });

        confirmPasswordFld.setBackground(new java.awt.Color(240, 240, 240));
        confirmPasswordFld.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        confirmPasswordFld.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        confirmPasswordFld.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true), "Confirm Password", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 12))); // NOI18N
        confirmPasswordFld.setVisible(false);
        confirmPasswordFld.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                confirmPasswordFldKeyReleased(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setText("Security Question 1");
        jLabel1.setVisible(false);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("Security Question 2");
        jLabel3.setVisible(false);

        passStrength.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        passStrength.setVisible(false);

        nextBtn.setBackground(new java.awt.Color(0, 0, 0));
        nextBtn.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        nextBtn.setForeground(new java.awt.Color(255, 255, 255));
        nextBtn.setText("NEXT");
        nextBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextBtnActionPerformed(evt);
            }
        });

        passStrengthLabel.setEditable(false);
        passStrengthLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        passStrengthLabel.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        passStrengthLabel.setBorder(null);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(238, 238, 238)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(question2Fld, javax.swing.GroupLayout.PREFERRED_SIZE, 487, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(questionFld, javax.swing.GroupLayout.PREFERRED_SIZE, 487, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1)
                            .addComponent(jLabel3))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(usernameFld)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(167, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(passwordFld, javax.swing.GroupLayout.PREFERRED_SIZE, 620, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(passStrength, javax.swing.GroupLayout.PREFERRED_SIZE, 466, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(passStrengthLabel))
                        .addComponent(confirmPasswordFld, javax.swing.GroupLayout.PREFERRED_SIZE, 617, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(189, 189, 189))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(390, 390, 390)
                        .addComponent(nextBtn1, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(393, 393, 393)
                        .addComponent(nextBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(usernameFld, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(nextBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(questionFld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(question2Fld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(nextBtn1, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(passwordFld, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(passStrengthLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 23, Short.MAX_VALUE)
                    .addComponent(passStrength, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(confirmPasswordFld, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("SECURITY Svcs");
        jLabel2.setToolTipText("");

        updateBtn.setBackground(new java.awt.Color(0, 0, 0));
        updateBtn.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        updateBtn.setForeground(new java.awt.Color(255, 255, 255));
        updateBtn.setText("Update");
        updateBtn.setVisible(false);
        updateBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateBtnActionPerformed(evt);
            }
        });

        passToolTip.setEditable(false);
        passToolTip.setColumns(20);
        passToolTip.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        passToolTip.setLineWrap(true);
        passToolTip.setRows(10);
        passToolTip.setText("-Password should be 8-32 characters long.\n-Password should include atleast 1 uppercase and 1 lowercase letter.\n-Password should include 1 number and 1 symbol.");
        passToolTip.setToolTipText("");
        passToolTip.setWrapStyleWord(true);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(passToolTip, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(395, 395, 395)
                                .addComponent(updateBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(passToolTip, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addComponent(updateBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void usernameFldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_usernameFldKeyReleased
        // TODO add your handling code here:
        int position = usernameFld.getCaretPosition();
        usernameFld.setText(usernameFld.getText().toLowerCase());
        usernameFld.setCaretPosition(position);
    }//GEN-LAST:event_usernameFldKeyReleased

    private void passwordFldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_passwordFldKeyReleased
        // TODO add your handling code here:
        String inputPassword = passwordFld.getText();
        String strength = frame.main.checkPassStrength(inputPassword);
        if(DEBUG_MODE == 1) System.out.println(strength);

        switch(strength) {
            case "Strong":
                passStrength.setValue(100);
                passStrength.setForeground(new Color(17, 107, 20));
                passStrengthLabel.setForeground(new Color(17, 107, 20));
                break;
            case "Good":
                passStrength.setValue(60);
                passStrength.setForeground(Color.blue);
                passStrengthLabel.setForeground(Color.blue);
                break;
            case "Fair":
                passStrength.setValue(30);
                passStrength.setForeground(Color.orange);
                passStrengthLabel.setForeground(Color.orange);
                break;
            case "Weak":
                passStrength.setValue(20);
                passStrength.setForeground(Color.red);
                passStrengthLabel.setForeground(Color.red);
                break;
            default:
                passStrength.setValue(0);
                passStrength.setForeground(Color.red);
                passStrengthLabel.setForeground(Color.gray);
                break;
        }
        
        passStrengthLabel.setText(strength);
        revalidate();
    }//GEN-LAST:event_passwordFldKeyReleased

    private void questionFldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_questionFldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_questionFldActionPerformed

    private void confirmPasswordFldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_confirmPasswordFldKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_confirmPasswordFldKeyReleased

    private void nextBtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextBtn1ActionPerformed
        // TODO add your handling code here:
        if (sqlite.validateSecQues(usernameFld.getText(), questionFld.getText(), question2Fld.getText())) {
            passwordFld.setVisible(true);
            confirmPasswordFld.setVisible(true);
            updateBtn.setVisible(true);
            passStrength.setVisible(true);
        }
        else
            JOptionPane.showMessageDialog(null, "Error: Security question answer is wrong.", "Error: Forget Password", JOptionPane.ERROR_MESSAGE);
    }//GEN-LAST:event_nextBtn1ActionPerformed

    private void updateBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateBtnActionPerformed
        // TODO add your handling code here:
        boolean valid = true;
        if (!passwordFld.getText().equals(confirmPasswordFld.getText())) {
            valid = false;
            JOptionPane.showMessageDialog(null, "Error: Passwords do not match.", "Error: Forget Password", JOptionPane.ERROR_MESSAGE);
        }
        // if password is strong enough
        switch(frame.main.checkPassStrength(passwordFld.getText())) {
            case "Strong":
                break;
            default:
                valid = false;
                JOptionPane.showMessageDialog(null, "Error: Password is too weak.", "Error: Forget Password", JOptionPane.ERROR_MESSAGE);
                break;
        }
        
        if (valid) {
            sqlite.updatePassword(usernameFld.getText(), passwordFld.getText());
            frame.main.sqlite.addLogs("UPDATE", usernameFld.getText(), "Password updated.");
            JOptionPane.showMessageDialog(null, "Notice: Update successful.", "Notice: Forget Password", JOptionPane.PLAIN_MESSAGE);
            frame.loginNav();
        }
    }//GEN-LAST:event_updateBtnActionPerformed

    private void passwordFldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_passwordFldFocusGained
        // TODO add your handling code here:
        passToolTip.setVisible(true);
    }//GEN-LAST:event_passwordFldFocusGained

    private void passwordFldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_passwordFldFocusLost
        // TODO add your handling code here:
        passToolTip.setVisible(false);
    }//GEN-LAST:event_passwordFldFocusLost

    private void questionFldMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_questionFldMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_questionFldMouseClicked

    private void nextBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextBtnActionPerformed
        // TODO add your handling code here:
        if (this.sqlite.doesUserExist(usernameFld.getText())) {
            usernameFld.setEditable(false);
            jLabel1.setVisible(true);
            jLabel1.setText(this.sqlite.getUserSecQues(usernameFld.getText()).get(0));
            questionFld.setVisible(true);
            jLabel3.setVisible(true);
            jLabel3.setText(this.sqlite.getUserSecQues(usernameFld.getText()).get(1));
            question2Fld.setVisible(true);
            nextBtn1.setVisible(true);
        }
        else
            JOptionPane.showMessageDialog(null, "Error: Username not found", "Error: Forget Psssowrd", JOptionPane.ERROR_MESSAGE);
    }//GEN-LAST:event_nextBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField confirmPasswordFld;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton nextBtn;
    private javax.swing.JButton nextBtn1;
    private javax.swing.JProgressBar passStrength;
    private javax.swing.JTextField passStrengthLabel;
    private javax.swing.JTextArea passToolTip;
    private javax.swing.JTextField passwordFld;
    private javax.swing.JTextField question2Fld;
    private javax.swing.JTextField questionFld;
    private javax.swing.JButton updateBtn;
    private javax.swing.JTextField usernameFld;
    // End of variables declaration//GEN-END:variables
}
